### ISSUE TITLE
SpotFleet対応

### ISSUE THREAD

**Issue by selmertsx** [speee/webapp-revieee#6]

**Comment by selmertsx** [comment]
ここらへん読んでる

http://aws.typepad.com/sajp/2016/01/powering-your-amazon-ecs-clusters-with-spot-fleet.html
https://aws.amazon.com/jp/blogs/compute/dynamic-scaling-with-ec2-spot-fleet/
http://docs.aws.amazon.com/ja_jp/AmazonECS/latest/developerguide/cloudwatch_alarm_autoscaling.html

Auto Scaling と Spot Fleetは両方セットで運用することになりそう。

**Comment by selmertsx** [comment]
最初は AutoScalingまで対応はしない。

http://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-spotfleet.html

**Comment by selmertsx** [comment]
設定を考える上で必要なもの

## SpotFleet Config
http://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-spotfleet-spotfleetrequestconfigdata.html

## Spot Fleet Launch specifications

http://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-spotfleet-spotfleetrequestconfigdata-launchspecifications.html

**Comment by selmertsx** [comment]
```yml
AllocationStrategy: lowestPrice
ExcessCapacityTerminationPolicy: noTermination
IamFleetRole: # IAM Role作って、ここにいれる
LaunchSpecifications:
  - 
SpotPrice: #m4のオンデマンド価格を入れとく
TargetCapacity: 3
TerminateInstancesWithExpiration: Boolean
ValidFrom: String
ValidUntil: String
```

## 追加調査項目
ExcessCapacityTerminationPolicy が valid values `noTermination | default` となってるけれども、
defaultがどういう挙動するのか
