### ISSUE TITLE
【HELP】Make task_definition settings easy.

### ISSUE THREAD

**Issue by selmertsx** [speee/webapp-revieee#66]
## Problem
Person who want to use "Revieee"  prepare the following settings for their products.
In order to make this setting, person need to know not only docker but also ECS.

```
family: sample-family
container_definitions:
  -
    name: main
    image: xxxx.dkr.ecr.ap-northeast-1.amazonaws.com/sample/rails:latest
    port_mappings:
      -
        protocol: tcp
        container_port: 3000
        host_port: 0
    environment:
      -
        name: BRANCH
        value: master
    links:
      - db
    memory: 512
    readonly_root_filesystem: false
    privileged: false
    log_configuration:
      log_driver: awslogs
      options:
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: xxxxx
        awslogs-group: xxxxx
  -
    name: storage
    image: xxxxx.dkr.ecr.ap-northeast-1.amazonaws.com/sample/storage:latest
    memory: 4
    readonly_root_filesystem: false
    privileged: false
    log_configuration:
      log_driver: awslogs
      options:
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: xxxx
        awslogs-group: xxxx
  -
    name: db
    image: xxxx.dkr.ecr.ap-northeast-1.amazonaws.com/sample/db:latest
    environment:
      -
        name: MYSQL_ALLOW_EMPTY_PASSWORD
        value: 'yes'
    volumes_from:
      -
        source_container: storage
    readonly_root_filesystem: false
    privileged: false
    memory: 256
    log_configuration:
      log_driver: awslogs
      options:
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: xxxxx
        awslogs-group: xxxxx
```

## Definition of done
- [ ] Make task_definition settings easy, and write document.
- [ ] create issue.
